### ISSUE TITLE
Use mc:edit

### ISSUE THREAD

**Issue by dandv** [charlesmudy/responsive-html-email-template#11]
`mc:edit` allows for editable areas: http://kb.mailchimp.com/templates/code/create-editable-content-areas-with-mailchimps-template-language

**Comment by charlesmudy** [comment]
@dandv can you work on this and make a pull request?

**Comment by dandv** [comment]
I'm just learning about this myself. https://github.com/digidem/email-templates uses `mc:edit`.

**Comment by charlesmudy** [comment]
@dandv do you have experience with MC? I can work on it from my end, shouldn't take more than an hr (including testing). We have similar feature like hideable tag :)
