### ISSUE TITLE
Blueprint w/o inline styling?

### ISSUE THREAD

**Issue by cschroeter** [charlesmudy/responsive-html-email-template#13]
Hey, 
first of all great job. The template looks great in all major devices (tested on Litmus).

Is there a version available without inline styled tags? I would like to develop a mail template like a normale "website" and then do the inline styling afterwards (Juice).

Cheers

**Comment by charlesmudy** [comment]
@cschroeter thanks, unfortunately there is no version without inline styling. You would have to strip it off manually yourself.
