### ISSUE TITLE
Columns not collapsing on Android 4.4.4 

### ISSUE THREAD

**Issue by TomHartney** [charlesmudy/responsive-html-email-template#18]
Firstly great template - out off the many I tested this is the simplest and works the best!
I am having issues with Android 4.4.4.
Screenshot attached is from the vanilla template (latest version as at 15 Sep 2015).
The right hand columns appear to collapse but the lefthand columns appear to stay fixed. 
Any suggested workarounds to this?
Thanks for all your hard work!
Tom
![android_444](https://cloud.githubusercontent.com/assets/13450274/9868909/982d1cce-5bc1-11e5-9c26-dd99bb876cb6.png)

**Comment by charlesmudy** [comment]
@TomHartney sorry I don't have time to test or work on this now, let me know if you found a fix.

**Comment by TomHartney** [comment]
Will do. I will repost if I find a workaround. Tom

**Comment by jvandenaardweg** [comment]
Just spend my day researching this problem for the company i work for, the result:

This is not possible on Android 4+. The native client does not support media queries. They switched to the "Gmail" render engine from what i could find on the interwebs, which does not allow media queries.

Templates should be made with the "mobile first" approach in mind. However, need to test this theory myself.

**Comment by malinabaj** [comment]
@TomHartney  Do you fixed your issue? If yes then please let me know.
