### ISSUE TITLE
Gmail: viewing half of the email

### ISSUE THREAD

**Issue by jonathanstarkey** [charlesmudy/responsive-html-email-template#19]
Charles,

First I'd like to say thanks for this amazing template.

Second when viewing this in Gmail for the desktop across all browsers it opens the email in like a 3/4 view. I have to pull my window open further for it to view the whole email.

Not sure if there was a coding solution to prevent that from happening.

Thanks,
Jonathan

**Comment by charlesmudy** [comment]
@jonathanstarkey tested it multiple time and my gmail works fine. Are you sure you're not using image size that is > than the width size?
