### ISSUE TITLE
responsive issues

### ISSUE THREAD

**Issue by sevensquare** [charlesmudy/responsive-html-email-template#20]
Hi,

I am looking for issues about this template.

I have some problems about mobile display.
Columns and containers should be displayed in 100% but aren't.
Please have a look on the enclosed screenshot :
(https://cloud.githubusercontent.com/assets/5775721/12422176/eedd7480-bec5-11e5-80a6-2234e4bd10fa.png)

Thanks in advance for your help,

pierre

**Comment by charlesmudy** [comment]
@sevensquare and thats the default without making any changes?

**Comment by sevensquare** [comment]
No change at all.

I send a test via mailchimp and this is how it looks on mobile device (in that case gmail on android)

**Comment by randavidovitz** [comment]
It looks to me, as if google (inbox) in my case, is removing/ignoring media queries.

**Comment by charlesmudy** [comment]
@randavidovitz but if that is the case, the column should still stay intact. How does that have to do with media query?

**Comment by randavidovitz** [comment]
I can't explain, but try reading the email in google inbox app (android )
and see.... this is a generic problem in majority of templates


Thoughts ?

**Comment by strukturedkaos** [comment]
@charlesmudy @randavidovitz @sevensquare - I'm seeing this responsive issue in the Mail app in iOS as well. Has anyone figured out a solution / workaround to this issue? 

![image2](https://cloud.githubusercontent.com/assets/528097/13377498/d0bfb878-ddab-11e5-86f8-0abe032e50c5.PNG)

**Comment by charlesmudy** [comment]
@sevensquare Mail IOS works fine for still, also make sure the original image size is not > than the width column. 

My thought is that you missed something, can you test the default template step by step, first with the default image and maybe replace it with yours (change the size)?

**Comment by triplemoons** [comment]
I can confirm this is not fully responsive for mobile applications. Gmail (along with many other email applications) does not read media queries. Responsive emails must be developed without relying on media queries.
