### ISSUE TITLE
Hybrid / Spongy?

### ISSUE THREAD

**Issue by TedGoas** [charlesmudy/responsive-html-email-template#21]
Any interest in making a [hybrid](https://www.emailonacid.com/blog/article/email-development/a-fluid-hybrid-design-primer) version of this?

**Comment by charlesmudy** [comment]
@TedGoas have you tested the demos? it doesn't even work well on regular gmail desktop.

**Comment by TedGoas** [comment]
So no Gmail support?

**Comment by charlesmudy** [comment]
Nope from what I saw, everything went 100% from 2 column grid.
