### ISSUE TITLE
Windows phone 8.1. support

### ISSUE THREAD

**Issue by mitja-p** [charlesmudy/responsive-html-email-template#22]
I tried and sent the default template to Windows phone built in email client. The fonts are really huge so the email is practically unreadable when opened. After clicking download all it is still unreadable. However if you go out of email and back in it than works perfectly. 
I am writing this just for people to know.

**Comment by charlesmudy** [comment]
@mitja-p if you can get the source code or forward me the email to info@charlesmudy.com so I can see what they're adding to the code on delivery.

**Comment by mitja-p** [comment]
I don't think anything is added. It seems that because the default email is quite big only partial download happens and the phone does not get the styling right. When you press download all, the styles are still broken. But exiting the email and going back in everything works, styles are as they should be. Also if you send smaller email everything works fine.
Still I have attached the source code (some href have been modified).
[resp_winphone8.1.zip](https://github.com/charlesmudy/responsive-html-email-template/files/229394/resp_winphone8.1.zip)
