### ISSUE TITLE
Outlook 2016 - blows out the background container

### ISSUE THREAD

**Issue by natalubs** [charlesmudy/responsive-html-email-template#23]
In the Outlook 2016 (Office 365) desktop application for PCs, the template blows out the background on either side of the email container. This makes it look like a blank email unless you use the horizontal scroll bar to find the body of the email way off to the right.

**Comment by dlc3172** [comment]
I'm not having this problem with Outlook 2016.

**Comment by natalubs** [comment]
![respmail-issue-example1](https://cloud.githubusercontent.com/assets/15054835/14683204/585b42b0-06de-11e6-9143-b4653416770e.JPG)

Here's a screenshot. The viewing pane seems to get forced into full width, so the content in the middle is way off to the right (on some screens you can't even see it, and it looks like a blank email). 

The behavior is tricky, though.
It doesn't happen in OWA, or on the Mac desktop client, and on the PC desktop client it doesn't happen all the time. I'll see it like this, then come back to my computer later and it will look just fine. When I restart Outlook it goes back to being weird.

**Comment by charlesmudy** [comment]
Right from my head without testing, can you set a fix with to the body, center tags @natalubs ?
