### ISSUE TITLE
Yahoo Mail - Left Margins Missing

### ISSUE THREAD

**Issue by dlc3172** [charlesmudy/responsive-html-email-template#24]
If you run this template through Yahoo Mail, you'll see that all the text runs right up to the left margin. It looks fine in other mail clients. Does anyone know how to fix this problem with Yahoo?

**Comment by dlc3172** [comment]
here is a screenshot of how it is appearing in Yahoo. You can see that the left margins are missing.

![image](https://cloud.githubusercontent.com/assets/18532496/14684271/3090eb08-06fd-11e6-9beb-361816a4a370.png)

**Comment by charlesmudy** [comment]
@dlc3172 what I usually do for testing is to experiment with developer tool (I use Chrome) by playing around with inline changes until it fits my design expectation ... then implement the code for real testing and comparing with other platforms.

Give that a try and let us know

**Comment by dlc3172** [comment]
Unfortunately, I'm not advanced enough to really know where to start. Do you have any suggestions as to what should be changed to maybe correct the problem? This must be a new problem with Yahoo, because I see in your code you originally tested your template with Yahoo.

**Comment by dlc3172** [comment]
@charlesmudy Unfortunately, I'm not advanced enough to really know where to start. Do you have any suggestions as to what should be changed to maybe correct the problem? This must be a new problem with Yahoo, because I see in your code you originally tested your template with Yahoo.

**Comment by charlesmudy** [comment]
@dlc3172 by playing with the body,center tag mergins, paddings, width size e.t.c.

**Comment by dlc3172** [comment]
Has anyone figured out how to fix the problem with Yahoo Mail? I haven't been able to figure it out myself.
