### ISSUE TITLE
Email Snippet in Android Mail

### ISSUE THREAD

**Issue by PENTAGON4** [charlesmudy/responsive-html-email-template#25]
Using Android 's mail program the email description displays beneath the Sender/Subject "Respmail is a responsive email....." instead of the first few lines of the email body.

**Comment by charlesmudy** [comment]
@PENTAGON4  I don't fully get it, mind sharing a screenshot?

**Comment by roflness** [comment]
@PENTAGON4 Is it possibly the invisible introduction? Try searching through your code for:

`id="invisibleIntroduction"`

Hope that was it, if not, like @charlesmudy said, a screenshot (or even your code) would help us determine where the issue could be.
