### ISSUE TITLE
font

### ISSUE THREAD

**Issue by mikezablu** [charlesmudy/responsive-html-email-template#26]
hi Charles!

How can I change the font to Robot from google fonts?

**Comment by roflness** [comment]
This worked for me:

https://www.campaignmonitor.com/resources/guides/web-fonts-in-email/

using: http://fonts.googleapis.com/css?family=Roboto

**Comment by mikezablu** [comment]
thanks rafael!

do you have a suggestion on which of the three methods to use? and given
that, would you mind teaching me where in the template to add the code?

*Miguel Zabludovsky*

Slate NYC | CEO

PERMISSION TO GET DIRTY
The fully-integrated, daily home + clothes cleaning service used by over
5,000 people in New York.

Get *your first week free* by clicking here <http://slatenyc.com/>.


[image: /admin/uploads/img/412/google.jpg]
<http://app.sigbuzz.me/l/L31/Wrp/>  473 Porter Avenue Brooklyn NY 11222

*W* slatenyc.com <http://app.sigbuzz.me/l/0jb/Wrp/> | *E *
miguel@slatenyc.com <mzabludovsky@slatenyc.com> |* T* (800) 573-8459
<%2B1%208005738459> | *M* (917) 287-4978 <%2B1%209172874978>

Connect with us:     <http://facebook.com/slatenyc>
<http://app.sigbuzz.me/l/Pjb/Wrp/>    <http://youtube.com/slatenyc>
<http://delicious.com/slatenyc>    <http://app.sigbuzz.me/l/Djb/Wrp/>
<http://www.yelp.com/biz/slate-nyc-new-york-2>

Email disclaimers are assumed to be a wise precaution. But they are mostly,
legally speaking, pointless. Lawyers and experts on internet policy say no
court case has ever turned on the presence or absence of such an automatic
e-mail footer in America, the most litigious of rich countries.  Many
disclaimers are, in effect, seeking to impose a contractual obligation
unilaterally, and thus are probably unenforceable. This is clear in Europe,
where a directive from the European Commission tells the courts to strike
out any unreasonable contractual obligation on a consumer if he has not
freely negotiated it. And a footer stating that nothing in the e-mail
should be used to break the law would be of no protection to a lawyer or
financial adviser sending a message that did suggest something illegal.

-The Economist (visit the link <http://app.sigbuzz.me/l/Mjb/Wrp/>)


 This email signature has been Crafted by SigBuzz
<http://www.sigbuzz.me/?utm_source=craftedbysb&utm_medium=emailfooter&utm_campaign=craftedbysb>

**Comment by roflness** [comment]
I used the import option.

In the <head> of your code, if you haven't already created <style> tags, this is how you can include it

`<head>
  <style type="text/css">
    @import url('http://fonts.googleapis.com/css?family=Roboto');
    html * { font-family:'Roboto' !important; }
  </style>
</head>`

I usually do inline styling, but html * should be how you apply it globally to a page. 

ref: http://stackoverflow.com/questions/7025756/how-to-apply-global-font-to-whole-html-document
