### ISSUE TITLE
White space column in Mailbox app

### ISSUE THREAD

**Issue by limeybloke** [charlesmudy/responsive-html-email-template#7]
Hello, I've come across a problem with a HTML email we've been building based on your framework. However I've also noticed this bug appears to be a problem with other emails I have received and wondered if you could shed any light on the subject. It doesn't occur with every email I get - some work which suggests there is a bug in your framework.

In short, when some responsive emails in the Mailbox App client on IOS, can be scrolled to the left revealing a white column. So the email doesn't in fact fit the 100% width. It's more like 110%.

I've attached a screenshot showing when I've scrolled left to reveal the White column.
![image](https://cloud.githubusercontent.com/assets/2025579/6317938/81d6569e-ba6c-11e4-95ba-43eede8d8fc7.jpg)

**Comment by charlesmudy** [comment]
Hi there, I cannot test it now but my guess is the issue might be coming from the wrapper #bodyCell e.t.c.  I'll get back to you when I have more time to dig into it.

**Comment by limeybloke** [comment]
Hi Charles, Did you manage to get anywhere with this? I received an email from Shopify that didn't have this issue so it must be something in the width issue.

**Comment by charlesmudy** [comment]
The issue might be from Mailbox, can you share a screenshot from the Shopify? a possible fix is adding padding 0 !important to the body tag but that makes the content shift to the left.

**Comment by charlesmudy** [comment]
I have commit an update to fix the space issue. Here is the fix for Mailbox to centre the contents, add this code inside the media query
```
/* MOBILE STYLES */
@media only screen and (max-width: 480px){
body{width: 100% !important; width: 281px !important; margin:auto !important;}
......
```
The side effect is that it sets the maximum screen to that size but I want it full screen, so I won't scarifies that for Mailbox (not included in the update). For some reason, full screen doesn't work on Mailbox.

**Comment by limeybloke** [comment]
That's not really a fix though as you're just setting a fixed width to it. What I don't understand is how Shopify are making this work? Can you review one of their newsletter emails?

**Comment by charlesmudy** [comment]
Yes it is fix, I checked Google newsletter and similar ones - they all have the fixed width for mobile. I'll look into it more when I have some time.

![img_0351](https://cloud.githubusercontent.com/assets/1445007/6389144/9ac77cd6-bda1-11e4-990d-68a0137d7251.PNG)

**Comment by limeybloke** [comment]
That's not worked. I've now got a white column down the left edge of the email when it opens.

![img_1892](https://cloud.githubusercontent.com/assets/2025579/6390036/fc9b82c8-bda0-11e4-8495-9f7d10d4a826.PNG)

**Comment by charlesmudy** [comment]
I can still see padding on your html body, pull the latest commit and add the code above inside your media query body tag.
