### ISSUE TITLE
Rendering issues in Gmail app (Android)

### ISSUE THREAD

**Issue by mrcasual** [charlesmudy/responsive-html-email-template#9]
Wrapper is set to 600px. There's no way to scroll to the right. 

![screenshot](https://cloud.githubusercontent.com/assets/2430296/6759700/65b7c892-cf18-11e4-9648-5089a0a6802f.png)

**Comment by charlesmudy** [comment]
And when it's not set to 600, it works nicely?

**Comment by charlesmudy** [comment]
And when it's not set to 600, it works? If so then there must be an issue from your side

**Comment by mrcasual** [comment]
Yes, it works at 500. I was trying to follow the following instructions:

```
** Quick modification **
We are using width of 500 for the whole content,
you can change it any size you want (e.g. 600).
````

**Comment by charlesmudy** [comment]
So I think you did something wrong, you want to share your code?

**Comment by mrcasual** [comment]
Sure: https://gist.github.com/mrcasual/3bc0f0d9eb15033184b6

**Comment by fragdieb** [comment]
Exactly the same problems when altering your code to 600px width.
Did you solve this?

**Comment by kayspiegel** [comment]
I'm working with a 600px variant myself and it works perfectly. Also your gist seems to work. Can't find any issue. Tested on iPhone6, Safari and Chrome as well as on Desktop.

**Comment by mrcasual** [comment]
Try Android...;

**Comment by kayspiegel** [comment]
Yes, works on Android. I haven't tested your layout but the one I adapted, also to a width of 600px. Let me have look tomorrow morning as soon as I get my hands on the Android in the office. Have you tested the Chrome Inspector Device Preview? This one looks fine here.

**Comment by mrcasual** [comment]
Also check on both 4" and 5" devices that are running KiktKat and Lollipop. The screenshot above is KitKat on 5" using the gist that I've attached. Not sure what setup @fragdieb has. 

If your layout works, please share the code and I'll test it.

**Comment by AaronGaim** [comment]
Confirm, not working on android browser :(
